name: CICD

on:
  push:
    branches:
      - main
      - WeatherApplication 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore Dependencies
        run: |
          cd DistributedWeatherApplication
          dotnet restore --verbosity normal
          cd ..
      - name: Build
        run: |
          cd DistributedWeatherApplication
          dotnet build --configuration Release --verbosity normal
          cd ..
      - name: Run Tests
        run: |
          cd DistributedWeatherApplication
          dotnet test --verbosity normal
          cd ..

