name: CI

on:
  push:
    branches:
      - main
      - WeatherApplication 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore Dependencies
        run: dotnet restore  # Restore project dependencies

      - name: Build
        run: dotnet build --configuration Release --project ./DistributedWeatherApplication/DistributedWeatherApplication/DistributedWeatherApplication.csproj
