name: CI
on:
  push:
    branches:
      - WeatherApplication

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.1' # Ensure this matches your project's requirements
  
    - name: Restore Dependencies
      run: dotnet restore
  
    - name: Build Project
      run: dotnet build --configuration Release
  
    - name: Run Tests
      run: dotnet test --configuration Release --verbosity normal

